create table t_pizza(
    id number generated by default as identity,
    sabor varchar(50),
    tamanho varchar(1),
    obs varchar(50),

    primary key(id)
);

create table t_venda_pizza(
    id number generated by default as identity,
    id_pizza number,
    ds_venda varchar(100),
    valor float,
    dt_venda date,

    foreign key (id_pizza) references t_pizza(id),
    primary key(id)
);


CREATE SEQUENCE seq_t_pizza START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_t_venda_pizza START WITH 1 INCREMENT BY 1;


drop table t_pizza;
drop table t_venda_pizza;